spring.application.name=flores-del-valle
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://localhost:5432/floristeria
spring.datasource.username=postgres
spring.datasource.password=D@nilo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
